language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1
  - 2.2
  - 2.3
  - rbx-2
  - rbx
  - jruby-9.0.5.0
script: bundle exec rake test
env:
  matrix:
    - DEVISE_ORM=active_record
    - DEVISE_ORM=mongoid
gemfile:
  - Gemfile
install: "travis_retry bundle install"
services:
  - mongodb
matrix:
  include:
    - rvm: 2.3.0
      gemfile: gemfiles/Gemfile.rails-master
      env: DEVISE_ORM=active_record
    - rvm: 2.3.0
      gemfile: gemfiles/Gemfile.rails-master
      env: DEVISE_ORM=mongoid
