language: ruby

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-6.0-beta
  - gemfiles/Gemfile.rails-5.2-stable
  - gemfiles/Gemfile.rails-5.0-stable
ß
matrix:
  exclude:
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile.rails-6.0-beta
    - rvm: 2.4.5
      gemfile: gemfiles/Gemfile.rails-6.0-beta
    - env: DEVISE_ORM=mongoid
      gemfile: Gemfile
    - env: DEVISE_ORM=mongoid
      gemfile: gemfiles/Gemfile.rails-5.0-stable
    - env: DEVISE_ORM=mongoid
      gemfile: gemfiles/Gemfile.rails-5.2-stable
    - env: DEVISE_ORM=mongoid
      gemfile: gemfiles/Gemfile.rails-6.0-beta
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/Gemfile.rails-6.0-beta

services:
  - mongodb

sudo: false

cache: bundler

env:
  matrix:
    - DEVISE_ORM=active_record
    - DEVISE_ORM=mongoid

before_install:
  - gem update --system
  - gem install bundler

before_script: "bundle update"

script: bundle exec rspec spec
