language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4
  - 2.5
  - 2.6
script: bundle exec rspec spec
env:
  matrix:
    - DEVISE_ORM=active_record
    - DEVISE_ORM=mongoid
gemfile:
  - Gemfile
install: "travis_retry bundle install"
services:
  - mongodb
matrix:
  include:
    - rvm: 2.6.0
      gemfile: gemfiles/Gemfile.rails-master
      env: DEVISE_ORM=active_record
    - rvm: 2.6.0
      gemfile: gemfiles/Gemfile.rails-master
      env: DEVISE_ORM=mongoid
